### ISSUE TITLE
MacOS build of newer release?

### ISSUE THREAD

**Issue by borderlineinteractive** [alloystorm/dvvr#10]
Dear developers,

I only found a MacOS version for build 0.1.1. Are you planning to release a newer MacOS version? 

As an alternative, I tried to run the newest Windows build on parallels, however, for some reason I was not able to load the content folders. I just copied the directory structure that was working with the MacOS build, but the windows build says that it does not find the motion, although the motion folder is displayed and contains the files that worked fine with the MacOS build.

Thank you very much.

**Comment by alloystorm** [comment]
Sorry for being late in responding to this. 

We only stopped publishing macOS builds because we thought nobody was interested in. It still works perfect on mac since it is developed on it. We will release the latest mac builds soon. 

But the content folder issue most likely has nothing to do with mac or pc, there shouldn't be any difference on those platforms in that part. Please check if you have at least one VMD motion with its audio file in the motion folder. Also please make sure that all files are not marked as read-only or hidden.  We had another user had similar issue and it turned out to be some of the texture files are read-only on PC but not on mac.

**Comment by alloystorm** [comment]
Having a bit problem with the latest Unity mac build. We might not be able to release the mac build soon. Maybe not until Unity 2019.3 goes out of beta.

**Comment by alloystorm** [comment]
Closing this since the issue in OP is most likely due to the permission setting of particular files in the content folder and has nothing to do with Mac builds. Due to the lack of interest we are no longer providing mac builds. Feel free to make another feature request if you think Mac version is important to you.
