### ISSUE TITLE
Can't load scenes and customizations

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#104]
Hi !

I need to check if this is only occuring for me but...

I can't load any of the scenes I saved before your last version.
And I believe every "texture on/off + tex parameters + morph" etc customizations were saved in those scenes ?
I had hundreds of models customized 1 by 1 and it had been all reseted in the last version so I was pretty shocked.

Wish it can be solved out ! Thanks !

**Comment by alloystorm** [comment]
Really sorry for the disruption. 

The scene data format is changed so old saves will not work. 

The same goes for the texture settings. Since the introduction of texture grouping, the save file structure is different now... 

We might be able to recover some of the texture settings from the old format in the next release but you'll need to backup your config files in order to avoid them from being overwritten by the new version.

**Comment by hboxgames** [comment]
Oh shoot I got it
I guess we gotta accept that for a on-going development  !
