### ISSUE TITLE
[DVVR 0.9] Problem with the texture in the zip

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#119]
There a problem with the texture in the zip, some of the model show red and white texture in some part of the model.

![Capture](https://user-images.githubusercontent.com/49305586/115329667-9d203c80-a160-11eb-910f-9f80c42b18f7.PNG)

![Capture 2](https://user-images.githubusercontent.com/49305586/115329682-a14c5a00-a160-11eb-9152-dac7eb2d4bf2.PNG)

**Comment by alloystorm** [comment]
Sounds like problem with filename encoding, is there Japanese or Chinese characters in the filename? If that's the case you might need to unzip it or edit the model to rename those texture files. Zip does not support Unicode very well.

**Comment by alloystorm** [comment]
Thanks for updating the issue. 

We figured out how to apply different encoding when reading ZIP files, but the program needs to know what exactly the encoding is before this can work. 

We will add a workaround in the next release for the users to label the encoding of the ZIP files so that program knows what encoding to use. To do this you'll need to add ".gb2312" (if the zip contains Chinese files) or ".jis932" (if there are Japanese characters) to the end of the filename. eg. if the zip file is "2b.zip", and there are Chinese named files inside the zip, then change the zip file to "2b.gb2312.zip", and refresh your content, the program will then be able to decode the ZIP correctly.

**Comment by Terell2018** [comment]
How do i change it to gb2312.zip

**Comment by alloystorm** [comment]
Fixed in 0.9.3
Here is the instruction on how to set encoding: https://vrstormlab.com/pages/zip_format.html

**Comment by Terell2018** [comment]
Jis932 and gb2312 is working but there is one problem is the model that is show in second image that i put jis932 and gb2312 but it not working and the texture in zip is not in Japanese or Chinese.
