### ISSUE TITLE
Problems about the New Version 1.1

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#141]
Hello !

Thank you for great features as always.

I just wanted to have a serious question about if the changes in the new version are worth or not. Overall, many changes happens, even where it was more convenient before. Here are some issues I am very doubtful : 

1 - **All materials reseted**. I asked while ago if these methods could change in the future, and you were pretty sure it won't. So I made customization to thousands of models and now they are reseted. I don't know what purpose is it for, and I really wonder if it is worth. It is possible **that I'd just stick to 1.0.1 and don't make further updates personnally.**

2 - **transparency** : the alpha was working great, just needed to manually set some stuffs sometime, but now it's not even usable. We still need to set things manually, so nothing improved but the alpha slider disapeared, and for example, any materials that aren't "hidden" but put in 0 alpha in order to be used in morph etc, are impossible to adjust.

3 - **Motion improvement**. The video you were showcasing with Wiggle wiggle was amazingly improved in terms of motion accuracy, but when I loaded myself, it didn't change from before. Is it not implemented yet ?

4 - **camera rotation** - the options to block camera rotations are still not working

Overall, the biggest issue for me is not giving choice of major changes in terms of menu or material loadings work. If you can give a "use old method" / "use new method" choice to check/uncheck in the soft, then it would be a big reflief.

That's it, still, I'm enjoying what you're doing and I thank you for it !

**Comment by alloystorm** [comment]
Sorry for the disruption. We are being very careful in making changes to material settings but the new name change that caused "all materials reseted" was necessary because the old naming leads to problems when multiple materials use the same name. 

Also comes with the 1.1 change is that it uses a different settings file location than previous versions, so in theory you can use pre and after 1.1 versions simultaneously without breaking settings for each since they will use 2 different files. 

The missing alpha setting is a bug, will get that fixed in the next release.

For the wiggle wiggle motion, sorry we forgot to mention that there is a new setting to allow motion like this to work properly. Under motion settings there is a new "Center Offset". By default the value is zero but if you have motion that moves unnaturally you can increase that value until the motion looks good. For the Wiggle wiggle video we are setting it at 0.25. 

4. will be looking into that as well. 

Sorry again for the trouble.

**Comment by hboxgames** [comment]
Hi !

Thanks for the explanation ! I understand that it was a major fix changing the whole thing ... were there no way to do it while keeping the Check/uncheck of the previous material settings tho ?

Oh, got it for the alpha and motion as well !

Thank,s and cheers !!

**Comment by hboxgames** [comment]
@alloystorm  
-plus, for now it's not only impossible to read the previous versions' material settings, but also inside the new version.  Like saving a scene within 1.1version and opening it, resets all settings anyway.
-Motions like this were only working properly if I uncheck "center offset" and "feet adjustment" in previous version, but were working. Now even if I uncheck it doesn't !
https://we.tl/t-1XzlXSgZHv

**Comment by alloystorm** [comment]
Sorry I missed the file transfer deadline, can you send it again?

**Comment by hboxgames** [comment]
Sure !
HEre's one of those : https://we.tl/t-94NRErw3uE

**Comment by alloystorm** [comment]
Closing this since most of the issues are addressed except the camera rotation. Will create a separate issue for that.
