### ISSUE TITLE
Using outfits and reflections in version 1.1.1 not working right

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#153]
**Describe the bug**
1)	The Stocking Shape in the Outfit settings, only effects the Stocking Surface and not the Masked Surface anymore.
2)	And as the “Masked Surface ” the “original” doesn’t work anymore.
3)	Strange artificing under characters with reflections on
(See Videos)

**To Reproduce**
Problem 1:
1. Go to Outfits in a character
2. Select an tattoo
3. select an masked Surface and change the Stocking shape
4. See how the Stocking Surface changes but the Masked Surface doesn’t.

Problem 2:
1. Go to Outfits in a character
2. Select an tattoo
3. select an masked Surface
4. you will notice that everything works except “Original” witch should be the original color (skin)

Problem 3:
1.	Go to graphics and set it to high. Then you see a strange area between character and the ground. (see video)
2.	Also when you look from horizontal to the floor you see an “line” where the reflections stop to work (sec 14-16 in vid 3)

**videos**
Problem 1+2:
I have loaded the same scene in 1.1.0 and 1.1.1
You can see in version 1.1.0 it works as expected “Original” is the skin color and the Stocking Shape effects the Stocking Surface and the Masked Surface
In version 1.1.0 however it doesn’t.

Version 1.1.0:

https://user-images.githubusercontent.com/85415360/138590254-5913deb6-9af7-4b7b-b168-0fa274a6c1cd.mp4

Version 1.1.1

https://user-images.githubusercontent.com/85415360/138590241-d6bfa8de-a78a-4275-a4a3-ad7e5fb0b645.mp4

Problem 3:
(strange area between character and the ground when reflections on)

https://user-images.githubusercontent.com/85415360/138590305-72398901-78d8-45f4-bbb8-ce1b624a0672.mp4

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version DanceXR HD Pro_win64_1.1.1.339

**Comment by alloystorm** [comment]
Thank you for taking the time writing the descriptions and making the videos. That's great effort!

The outfit shader has been modified in the 1.1.1 release to optimize the flow and reduce rendering cost. In doing so certain behaviour is sacrificed to make way for performance and simplicity. From your description the problem 1 is due to the masking area is not limited by the stocking shape, and 2 is due to the way color is generated. We'll review these again and see how much can we bring back. 

The problem 3 is SSR defect, this is just the technical limitation of screen space reflection. Use probe reflection will eliminate this but at a greater performance cost.

**Comment by alloystorm** [comment]
Fixed in 1.1.3
