### ISSUE TITLE
DanceXR not loading .SPH file

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#185]
<img width="733" alt="Screenshot 2022-06-12 183538" src="https://user-images.githubusercontent.com/107079307/173256508-4aee643f-9528-4716-b049-2663c10bcc1c.png">

This model the hair gets it color from the .SPH file

<img width="290" alt="Screenshot 2022-06-12 183902" src="https://user-images.githubusercontent.com/107079307/173256555-8e6b5df3-d74e-4a92-9fec-e89230298e9e.png">

This is what it looks like in DanceXR
I can email you the link to the file I put on tstorage.info if you need it

**Comment by alloystorm** [comment]
Thanks. SPH and SPA are ignored at the moment, I didn't know they can carry color information. Will look into it.

**Comment by Chrisc78** [comment]
<img width="908" alt="Screenshot 2022-06-18 222139" src="https://user-images.githubusercontent.com/107079307/174463217-67a80875-8817-48e4-83ba-e483f2be1f0f.png">

I should have shown what the texture file looked like.

**Comment by alloystorm** [comment]
It seems the dds texture format of that Tashigi model is not supported by Unity. There's not much we can do about it. That's why it's all white. 
The sph seems to be environment reflection map which we don't need because the reflection is controlled by the dynamic environment in Unity, and there's no where in the render pipeline we can specify a spherical reflection map for a material anyways. So we are not able to support sph textures.

**Comment by Chrisc78** [comment]
I found a solution for models that gets its color or  texture from the .sph file.
 1. for color you can simply use Diffuse Color. 
 2. If the texure is being loaded as a .sph file just convert it to a .png file and load it as a normal texture.
