### ISSUE TITLE
Vive controller issues reported by Digitrevx

### ISSUE THREAD

**Issue by alloystorm** [alloystorm/dvvr#19]
Couple issues with the vive. The first easy one is all the directional controls are reversed for the translation controller. The rotation and up and down movement seems to work fine in your private build. I hit bottom of track pad and go forward. The other issue seems to be related to if one of your controllers is not powered / seen / or detected at the time of loading a new character model the menu will be stuck with the character select window. You will not be able return to play menu. I'm not sure if its related to loosing the other controller's imputes forever at that point or what. I thought at first it was models that were breaking the app. But it seems to be more related to you gota be very very sure when you started the app you have both controllers and they are always in front of you and on at all times. And it seems to be very picky btw. I have to restart DVVR a few times to find the right combo of turning on controllers before or after the app launches to get both on.

The other issue with the vive is motion selection and moving. It's so so easy to change the motion by mistake when you move. In fact if you use the track pad to change a motion you will undoubtedly move. And it's not like a little. Some times it will send you off in this automated direction. Not sure if this is to do with the ease in and ease out effect of movement being used. But sometimes it seems to never stop going lol. But I understand using the track pads click and touch features to get more options on the controllers. Just some pit falls with how its set up atm.

**Comment by alloystorm** [comment]
Since Vive controller doesn't have a thumbstick, the axis input is from the touchpad. We use the axis value to control camera navigation but the values from a touchpad can be very volatile and not really suitable for thumbstick style input. 

In the next release we'll add a setting to block the axis input until the touchpad is pressed down. This should relieve the problem.

**Comment by alloystorm** [comment]
There is a new option in 0.5 that only takes touchpad input when it is pressed down. Vive users please have a try and let me know if the option solves the issue for you.

**Comment by alloystorm** [comment]
Can any vive user verify if the setting is working for you?

**Comment by Marvin42x** [comment]
I have a valve index. When I use the right controller to change my position I constantly switch the motions with it. I don't know what the reason is. I would also like to be able to reduce the sensitivity of the controller and preferably an option to switch off the sensor field of the controller. At the moment the sensor field and the joystick are working the same which leads to unwanted movements.
My controllers have touchpad and joystick.
The version 5.1 does not differ from the previous ones.
No reaction with press or not press.
these are my controllers:
https://cnet3.cbsistatic.com/img/ZhVi4MNzOOgTdt8a4vSBbZLJV-Q=/2019/05/30/8643381b-2c82-41cc-b34b-b5c83233790e/07-valve-index.jpg
Translated with www.DeepL.com/Translator (free version)

**Comment by alloystorm** [comment]
Closing this since the latest 0.5.2 has most of the control issues resolved. Feel free to open new issue if there are still problems.
