### ISSUE TITLE
Feature request Different models can use different VMD files at the same time

### ISSUE THREAD

**Issue by fulanfulanfu** [alloystorm/dvvr#196]
like koikatsu studio
model A use a.vmd and model B use b.vmd

**Comment by alloystorm** [comment]
In fact you can already do that. There are a douple scenarios. 

1) Multiple vmd motions for the same song. In this case you need to keep all the vmd files and the audio file in the same folder (or a zip package), and make sure there is only one audio file. We call this a "dance set". Once the dance set is loaded you can find all the motions in the list and assign them to different actors individually. It is important to organize your motion and audio together in the same folder because otherwise the scanner will treat each vmd and audio files as individual dance sets. 

2) If you have already loaded one dance set but wish to use motions from a different dance set for certain actors, you can do that too. We call this "remixing". If you have a dance set loaded already, you will see a "Load Remix" item from the motion menu. Use that to load your second dance set and then you can assign motions from it to your actors individually. 

Hope that explains it. Let me know if that doesn't cover your need or you have further questions.
