### ISSUE TITLE
Previous version standalone

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#197]
Hi !

I am reviving this issue since it is pertty important.
There is one thing I do not understand about the way it works. I have many issues with the new versions which is totally fine knowing that it is an app in on-going development. It is getting great and I look forward for its future.

But do you actually have an online-control over every previous versions you released ? I thought they were standalone offline apps that can simply be kept in case the new versions are problematic or when we don't want to update it.

I want to make sure about this, and have Working ealier versions which I can play with, while staying up to date about what you guys do on newer versions. A old version I can just "HAVE" without worrying that it somehow gets out of service randomly.

Right now I can't correctly get them lauched without getting buggy or grey screen.

Is this something I can request as a long term supporter ?

Thanks !

**Comment by alloystorm** [comment]
The old versions will continue to function, they won't expire or deprecate. However we won't be able to maintain them if new bugs or  compatibility issues with operating systems are discovered. All bug fixes can only go into the latest release. 

The real problem is with data, both saved configs and content cache. If you plan to share the same content library between multiple versions, there are chances that the data writen by new versions will not work well with the old ones. 

So either you'll have to separate the content libraries or backup and restore the data every time you switch versions. I'm afraid there is not much we can do in the short term to improve this.

In terms of where to get old versions, right now Patreon have all the past releases available. On Steam there is no easy way to revert back to old versions. We are planning to add beta and stable branches on Steam to allow swtiching between maybe the latest 3 versions in the future. On Itch.io we usually keep the latest 2 versions available for download.

**Comment by hboxgames** [comment]
Thank you for getting back !
I guess I needed to know how it function, so it is probably about having a separate content/config stuff all independant to the new ones. I will try that.
By the way, there are a lot of great features about the new versions thought like being able to add external mask etc.

Keep up the good work, thanks !

ps. I was thinking of posting a little bug report about the transparency rendering that is glitchy. Is that something you are already aware of ?

**Comment by alloystorm** [comment]
Feel free to raise it, I'll see if that's something we already know.
