### ISSUE TITLE
Outfit Material buggy on hdpro_1.3.4.635

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#206]
Hi !

Thanks for the great updates, and the secondary motion feature is really helpful to read facials/lips !

The Outfit function is acting a bit weird in this version by the way, although it was doing great in the one just before :
-When we use the mask option, the material is set on the first one for everything. so the mask isn't visible since the 2nd material doesn't affect anything. That's probably why my custom config save of the outfits are just turnt to simple black 
-The glow effect on the outfit doesn't react anymore

For now it's just these but I feel like the settings are being a bit confused right now ?

That's it ! Thanks !

**Comment by alloystorm** [comment]
Thanks!

The 2nd surface options is only used if you choose one of the "maze" patterns. In the grid pattern only the base and edge surface is used.
We will make the mask option more flexible in the next update. 
Yes the glow is a bit too weak due to lighting become much stronger in this version. Will icnrease its brightness in the next update.

**Comment by hboxgames** [comment]
Ah ! I see !
But I actually use Patterns I make myself on photoshop, and it worked really great !
So I would like them to react like the maze one if that is reacting with the 2nd surface like before !

**Comment by alloystorm** [comment]
Fixed in 1.3.5
