### ISSUE TITLE
Custom Texture map and Individual rotation

### ISSUE THREAD

**Issue by Edanwon** [alloystorm/dvvr#256]
Problems: 
1. Sometimes it's hard to figure out why some textures of the model couldn't get to work besides the file name encoding issue.
2. Maybe it's because of my clumsiness, but other than the formation that we can rotate actors as a group, or selected presets that have actors facing different directions, I seem not to be able to rotate actors individually to make them face whichever direction we want.
3. lack of Guide. Video guides on youtube are outdated and many of them use old UI which is hugely different from the current version.

Solution:
1. It'd be better if we can manually assign custom textures for materials and tweak them to the best look.
2. Adding a slider to each model for that feature, and it would be better if we can input the exact value instead of only dragging the slider.
3. Make an offline manual or something, inside the program or in the danceXR folder, or update the youtube manual.

**Comment by Benz10wheel** [comment]
You can rotate the character while holding grab button, then aim at a character and press and hold trigger button and move left and right with thumb stick. (yes you need to hold grab, click and hold trigger then move thumb stick left and right.

Also while rotating the character due to grab+thumbstick also rotate camera around your character will rotate while the cemera also rotate around which is a mess but you can sorta remap the button to avoid this I think.

**Comment by Edanwon** [comment]
> You can rotate the character while holding grab button, then aim at a character and press and hold trigger button and move left and right with thumb stick. Yes you need to hold grab, click at chracter and hold trigger then move thumb stick left and right.
> 
> Also while rotating the character due to grab+thumbstick also rotate camera around your character will rotate while the cemera also rotate around which is a mess but you can sorta remap the button to avoid this I think.

Oh, silly me, I didn't manage to make it in non-vr mode, glad to hear that it's already there. However, it can probably be better if we make it easier figure out how to do that in non-vr mode I guess? :D

**Comment by Benz10wheel** [comment]
For desktop mode its much easier just click and drag the character like how you wanted to move them, while doing that use mouse-wheel to scroll for rotation.

**Comment by Edanwon** [comment]
> 

Holy... Sure it can do that! I just realized how silly I was! I tried that once but it didn't work for me then I have never retried to do that ever again. Thank you so much.

**Comment by alloystorm** [comment]
Glad you figured out how to rotation work. Thanks Benz10wheel for your help!

We are updating our website this month, hope it is more clearer and easier to find information you need. https://vrstormlab.com/

For the missing textures, if it is not filename encoding or extra spaces, it could also be that the format is not supported. You can send us the model for further check if you couldn't figure it out.

I'll close this thread since there's not much left to follow up on. Feel free to raise another issue if anything comes up.
