### ISSUE TITLE
".Pose" Support - XnaLara Still Pose File Format

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#257]
**Is your feature request related to a problem? Please describe.**
Currently there seems to be no support for the ".Pose" file. ".Pose" files are still poses whereas ".VMD" are usually motion data.

**Describe the solution you'd like**
Support for ".Pose" still pose files.

**Additional context**
I've added a few ".Pose" files to test out, the Honoka poses also includes a preview picture showcasing those poses. The Ace Attorney one less so.
[XnaLara (.Pose) File Samples.zip](https://github.com/alloystorm/dvvr/files/11046205/XnaLara.Pose.File.Samples.zip)

**Comment by alloystorm** [comment]
Had a look at the pose files, the format seems fairly simple. 

How do you envisage using the still poses? Do you expect it to work like motions that you can load from the menu and apply to actors?

One thing with the XPS poses is that they are specific to a particular model since XPS don't have a standard bone structure. So the pose that works for one model likely won't work for others. We can try to translate the common bone names but it won't work for models that requires using the bone mapper.
