### ISSUE TITLE
Errors when I create videos with Creators

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#301]
<img width="785" alt="Screenshot 2023-12-03 071125" src="https://github.com/alloystorm/dvvr/assets/107079307/0294a550-d951-4eb3-8992-0df178350678">

Everytime I run Convert.bat I get this error.

<img width="863" alt="Screenshot 2023-12-03 071315" src="https://github.com/alloystorm/dvvr/assets/107079307/3e37c571-f677-42db-8449-4bc38e741098">

So i add " where needed.

<img width="539" alt="Screenshot 2023-12-03 070013" src="https://github.com/alloystorm/dvvr/assets/107079307/e2eea761-5114-4f3b-b9cc-bd2b9dc8fe34">

After it converts most videos can only open in VLC Media Player except for 180VR videos

**Comment by alloystorm** [comment]
The provided command is more like an example since there are different hardware and software configurations out there and there can be new updates of ffmpeg that break things. 

The idea is just to use your favourite tool to convert the image sequence to a video. 

We'll add the quotes around the file names but don't expect it to work 100%.
