### ISSUE TITLE
Stage Texture Issue - (DOA Crystal Boutique)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#312]
**Describe the bug**
Strange textures and all-white stages--no textures loading.

**To Reproduce**
1. Just load any stage listed at the bottom of this Issue filing.

**Expected behavior**
To look closer to the preview pictures from DeviantArt, and not strangely covered in "Hippie" or Austin Powers Era Flower Power Flower themes. No offense intended.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.5.0.

**Additional context**
Example of the correct appearance of the stage, Crystal Boutique by Deexie.
![doax2___crystal_boutique_by_deexie_d4bgkxl-414w-2x](https://github.com/alloystorm/dvvr/assets/31259717/ed500795-db53-4cf3-9e0c-b087662f4598)
Extra Details: Uses .MTL and .OBJ
https://www.deviantart.com/deexie/art/DOAX2-Crystal-Boutique-261114105

DOAX2 Casino by  Chrissy Tee
Details: Uses .DDS Image Format  --- Leading to All-White, not loaded textures.
https://www.deviantart.com/chrissy-tee/art/DoA-X2-Casino-scene-XPS-719870388

Dead Or Alive 5_Johnny's Dinner by Chrissy Tee
https://www.deviantart.com/chrissy-tee/art/Dead-Or-Alive-5-Diner-Reupload-719869778

**Comment by alloystorm** [comment]
A few separate issues here. 
* With the obj model within a zip package, this will be fixed in the next update.
* Wrong texture path, the Johnny's Diner model has incorrect texture paths. They are absolute paths from the creator's PC, which makes it impossible to find the files. 
* DDS format, DDS has many variants and not all of them are supported. The Casino and Johnny's Diner uses format that we don't support yet. Before we figure out that format the best chance is to convert them into different formats. DanceXR will try to search for files in different formats if the specified file is not found, so you can simply convert those dds images to png and delete the original dds files. Then DanceXR will be able to use those png images as alternative.
