### ISSUE TITLE
Blackness (Intermittent VR Display)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#322]
Version: 2024.1 (Via Itch.io App)
OS: Windows 11

Issue:
After simply loading the linked model VR video is blank/blackout depending on distance to model, ex. within a certain closeness picture is displayed and beyond that the blackness appears again.

Source:
https://www.deviantart.com/zareef/art/DOA5-LR-Mila-Aloha-bikini-529275531

**Comment by alloystorm** [comment]
Try turn on "Stop NaN", this is usually due to certain part of the model causing "NaN" error and that can break the entire scene.

**Comment by alloystorm** [comment]
Stop NAN is a workaround that prevent the whole screen to become black when there are shader errors. The error is ususally caused by problems in the model (like normal vector being 0 in certain areas) or effects. 
It's not good to set this on by default because it might hurt performance. We'll add more description in both the app and the documentation.
