### ISSUE TITLE
There are various bugs in DanceXR Raytracing PC SteamVR

### ISSUE THREAD

**Issue by Archlight199** [alloystorm/dvvr#382]
This was translated using GPT4o (KR->EN), there might be some inaccuracies.

PC DanceXR Raytracing (11.1440) was run in the following environment:
Windows 10, RTX 4080, Ryzen 7600, Meta Quest 2, Airlink, SteamVR.

1. Freefly camera move is not working when UI is on.

When running the game on Quest 2 via SteamVR and loading a model, if the UI is on, freefly camera doesn't work, making it impossible to move. I must turn off the UI and move the controller to control the camera. 

This case is very similar to https://github.com/alloystorm/dvvr/issues/332 issues.

It works normally when running on desktop, not in VR.

2. When the MMD Contents folder becomes excessively large (not certain, but approximately 70-80GB), upon initially loading a model, both the model and camera remain statically and do not move.

The issue is resolved only after switching the library to a different folder. This problem also frequently occurs only in SteamVR.

3. Since version 11.1440, There are cases where the UI does not close even when the VR controller button is pressed.

I must go to the controller settings and set the UI-related buttons to turn off the UI in order to return to normal operation. When combined with problem issue 1,2 , the camera and model is stopped while the UI is on.

And if the UI camera is turned off once without UI key setting it on the controller, nothing will be done after that. I am helpless and unable to do anything in this bug situation. All I can do is watch the spinning wooden floor LEDs, mockingly drifting clouds, and the glittering DanceXR statue. This functions normally when run in non-VR mode.

Previous versions (June and July 2024) rarely had these issues. It seems these problems have gradually emerged after updating to the latest version.

If I'm the only one experiencing these issues, how should I resolve them? Would it work normally if I delete the cache or completely remove the program folder, registry, etc.? If anyone knows the solution, please let me know.

**Comment by alloystorm** [comment]
The camera freeze is an intentional change. It's actually introduced a couple versions ago. 

Whenever UI is present, camera movement is locked. This is to ensure that no matter what motion you have, the UI is always accessible. Because when there's fast camera movements, it's impossible to control the UI easily.

Sometimes the mouse or pointer click seems unresponsive is because it is hitting the drag area of particle simulation, this is something we are going to work on to improve but it's not actually a bug. It's unfortunately a compromise between performance and interaction. You can turn off "Enable Dragging" in the cloth simulation settings and it might feel better.

**Comment by alloystorm** [comment]
Closing this for now since they are expected behviour and workarounds provided. Let us know if any further questions.
