### ISSUE TITLE
Hair sections missing

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#67]
Hair is missing a lot of pieces.  this happens on all models I tried.  Can you replicate this issue?  or is it something on my end?  

![bad hair](https://user-images.githubusercontent.com/54456572/85930985-47536e80-b886-11ea-96da-ba7fbc12289b.jpg)

**Comment by IngenVR** [comment]
![0 6 3Hairtype](https://user-images.githubusercontent.com/58618176/85934418-edea4e80-b91c-11ea-9de0-aff20920d59c.jpg)
left=0.6.3privateLW HairTexture Type:Hair
center=0.6.3privateLW HairTexture Type:Standard
right=0.6.3privateHD HairTexture Type:Hair

Try changing the HairTexture Type to Standard.
It may improve the problem.
I think the problem is caused by the addition of the HairShader in the HD version.

**Comment by chengsta** [comment]
Hey that fixed it, thanks!
