### ISSUE TITLE
Some Minor issues

### ISSUE THREAD

**Issue by jmew1989** [alloystorm/dvvr#76]
Hi ! 
Let me list a few minor issues I am experiencing after testing the program. Let me know if some of these are simply due to my unknowledgement of the fuctions !

-The option to look at the viewer could be strenghtened, for now it's not really doing a lot. The slider at max could kind of fix the head direction and/or sight toward camera (this is a personal wish)

-Model morphs aren't applying even if we move sliders. Especially those with clothe changing/removing fuctions

-Textures on MMD models are automatically applied to be "hair" or "standard" etc.. but rarely relevant. Some hair would look better in standard, and transparent part like highlights are opaque at loading. So I have to manually find every weird looking textures and set them, each time since we can't save that setting(as far as I saw)

-Dynamic is working great for XPS models but heavy on cpu, and MMD models have very weird, fuzzy dynamics

-General lighting/rendering is looking pretty good, but not as optimized as mocumocudance. Shadow/colors don't seem to help the MMD look in general. Hard to explain but the comparison is pretty strong.

Thank you anyway for developping such a easy to use and amazing tool !

**Comment by alloystorm** [comment]
The head-turning can be turned on by increasing the "Head Range" in "Eye Contact" settings. However, sometimes this can create strange head poses during dance move and this is why it is turned off by default. 

The latest 0.7.1a should have morph issues fixed. Please let me know if you are still having this issue in the latest version. 

The default material type is inferred from the material name, eg. if it contains "body" we set it as skin mode. Since the program can't understand what each material is for. We might be able to improve this a bit by updating the keywords but given most of the models use Japanese names there is really not much further we can do. Do you think it'll be better if we use standard mode for all? If so we might be able to add a setting to control the automatic behavior.

**Comment by jmew1989** [comment]
Thank you !
Indeed, for me textures and morph iseeus got overall pretty much fixed ! What I meant is that when a materia name was "hair" and got automatically switched in "hair shader", it looked bad, while standard looked ok. But in the new version I didn't see that problem anymore !!

About the eye-contact, I was juste wondering if there could be a "always-look-at" option, which isn't applied only when we watch ourselves. I thought it could work with a good limitation of head/eyes rotation, it does work decently in mocumocu !

Anyway thanks for the great new version !
