### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by jmew1989** [alloystorm/dvvr#84]
Hi !

Thanks for the great feature as always !

- First I just noticed a huge increase of latency between previous versions and the latest private version 7.2.. Just wanted to see if that's normal ?

- This is my main request, I was looking for a walkaround but couldn't find anything. Right now the Maximum I can have in "Eye range" is 1. Which I guess means character looks at camera "if" I look at it. I would really love that there is an option to get rid of that "if" and make them look constantly. Then I'm sure "eye limit" and "head range" adjustment should make it work just great.

- The new auto dance feature is just amazing. I work as a high end animator for feature film and VFX. Even though I don't have hella lot of time, I would love to help making more patterns if there's need, and can be worked on maya !

Thanks for the great stuff and good luck !

ps. Oh and this was a all-time issue for me, but just asking for information : Is it normal that the software crashes pretty easily and randomly while loading characters ? It happens like every 7~10 loading so I have to save quite often

**Comment by alloystorm** [comment]
Hi 
Thanks for the the message. 

So do you get lower fps than the previous version or do you get stutter from time to time? What's your average fps compared to the previous version? There was no graphical change this time so technically there shouldn't be any dramatic change on FPS. Sometimes physics also slows down frame rate quite a bit but it all depends on the model. Turning off reflection & reduce the number of lights can help fps a lot. 

With eye contact, the basic logic is that the actor looks at you when you are in their field of view and you are also looking at them. 
"Eye range" controls their field of view. Then "Eye limit" is applied to the final rotation to limit the eye movement, since for cartoon characters with big eyes the result can be weird when the eyes turn towards you completely. So for realistic characters, using 1 for both eye range and eye limit should give you what you needed but you still need to be in the general direction they are looking at for it to be triggered. 
"Head range" controls how much they turn their heads towards you. When blended with dance motion this sometimes creates a weird result so the default value is 0. My suggestion is to set it at 0.5. 

The current "auto dance" is purely "mathematical", it is controlled by periodical function with randomized parameters to rotate the body parts & apply offsets based on calculation. Yes going forward we can definitely use some help from animators like you. Thank you very much for offering help! In the past, I had a few attempts to create procedural walking motion but none were very realistic.

**Comment by jmew1989** [comment]
Oh I see, maybe I would try the LW version as well, but thanks for the advice !
Sure if you are trying something that needs to be implemented with animation we could talk !

And about eye contact, I think I didn't explain myself very well ... Indeed for now they look at the camera when you're in their field of view, but I was wondering if we could have an option to, for example, have this field of view to infinite, or the eyecontact triggered without condition so they are looking at camera constantly (it's an option in mocumocu actually)

Again thanks for the great stuff btw !

**Comment by alloystorm** [comment]
I see what you mean. That should be easy but personally, the way Mocu did it is a bit creepy, especially when there are multiple characters... Maybe we can add an option for this in the next version.

**Comment by jmew1989** [comment]
You're right your version is indeed more natural XD  I'd be curious to have an option though thanks !!
